export const data = [
  {
    'uuid' : '5d0dcf42-7830-4625-af3b-9969475ef78a',
    'flight' : {
      'flightSegments' : [ {
        'uuid' : 'fd65a7b1-54f8-4bbe-bfef-b03c2109e3cc',
        'airlineCode' : 'AA',
        'airlineName' : 'American Airlines',
        'operatingAirlineCode' : null,
        'operatingAirlineName' : null,
        'operatingFlightNumber' : '18',
        'flightNumber' : '18',
        'stopQuantity' : 0,
        'elapsedTimeMinutes' : 348,
        'departureDateAndTime' : '2018-07-05T06:25:00.000',
        'arrivalDateAndTime' : '2018-07-05T15:13:00.000',
        'estimatedDepartureDateTime' : null,
        'estimatedArrivalDateTime' : null,
        'departureTerminal' : null,
        'arrivalTerminal' : null,
        'departureAirportCode' : 'SFO',
        'arrivalAirportCode' : 'JFK',
        'airlineLogoUrl' : null,
        'flightClass' : 'ECONOMY',
        'airplaneName' : null,
        'carrierLocator' : null,
        'departureGate' : null,
        'departureGateChanged' : false,
        'arrivalGate' : null,
        'baggageClaim' : null,
        'status' : 'CONFIRMED',
        'fareClass' : 'K',
        'segmentNumber' : null,
        'seatsRemaining' : 9,
        'seatSelectionStatusCode' : null,
        'highResAirlineLogoUrl' : 'https://s3.amazonaws.com/tripactions-airline-logos/AA.png',
        'departureZonedDateTime' : '2018-07-05T06:25:00-07:00',
        'arrivalZonedDateTime' : '2018-07-05T15:13:00-04:00',
        'estimatedDepartureZonedDateTime' : null,
        'estimatedArrivalZonedDateTime' : null,
        'stopsString' : ''
      },
        {
          'uuid' : 'fd65a7b1-54f8-4bbe-bfef-b03c2109e3cc',
          'airlineCode' : 'AA',
          'airlineName' : 'American Airlines',
          'operatingAirlineCode' : null,
          'operatingAirlineName' : null,
          'operatingFlightNumber' : '18',
          'flightNumber' : '18',
          'stopQuantity' : 0,
          'elapsedTimeMinutes' : 348,
          'departureDateAndTime' : '2018-07-05T06:25:00.000',
          'arrivalDateAndTime' : '2018-07-05T15:13:00.000',
          'estimatedDepartureDateTime' : null,
          'estimatedArrivalDateTime' : null,
          'departureTerminal' : null,
          'arrivalTerminal' : null,
          'departureAirportCode' : 'SFO',
          'arrivalAirportCode' : 'JFK',
          'airlineLogoUrl' : null,
          'flightClass' : 'ECONOMY',
          'airplaneName' : null,
          'carrierLocator' : null,
          'departureGate' : null,
          'departureGateChanged' : false,
          'arrivalGate' : null,
          'baggageClaim' : null,
          'status' : 'CONFIRMED',
          'fareClass' : 'K',
          'segmentNumber' : null,
          'seatsRemaining' : 9,
          'seatSelectionStatusCode' : null,
          'highResAirlineLogoUrl' : 'https://s3.amazonaws.com/tripactions-airline-logos/AA.png',
          'departureZonedDateTime' : '2018-07-05T06:25:00-07:00',
          'arrivalZonedDateTime' : '2018-07-05T15:13:00-04:00',
          'estimatedDepartureZonedDateTime' : null,
          'estimatedArrivalZonedDateTime' : null,
          'stopsString' : ''
        }],
      'durationMinutes' : 348,
      'connectionCount' : 0,
      'mixedClass' : false,
      'basicEconomy' : false,
      'airFareType' : null,
      'valid' : true,
      'totalLayoverMinutes' : 0
    },
    'startingPrice' : {
      'basePrice' : 415.810000000000000000000000000000,
      'tax' : 45.390000000000000000000000000000,
      'agencyCurrency' : 'USD',
      'agencyCurrencyConversion' : 1,
      'sourceCurrency' : null,
      'sourceCurrencyConversion' : 0,
      'resortFee' : 0,
      'resortFeeDisclaimer' : null,
      'bookingFee' : 0,
      'tripFeeQuotes' : [ ],
      'vipFee' : 0,
      'exchangeAmount' : 0,
      'exchangeFee' : 0,
      'airlineFee' : 0,
      'creditCardFee' : 0,
      'startingPrice' : false,
      'points' : 0,
      'numDays' : 0,
      'cancelationPolicy' : null,
      'outOfPolicy' : false,
      'policyViolationList' : [ ],
      'totalPrice' : 461.200000000000000000000000000000,
      'totalNetCharge' : 461.200000000000000000000000000000,
      'currency' : 'USD'
    },
    'loyaltyCardUuid' : null,
    'applicableFFPrograms' : [ ],
    'promotion' : null,
    'bestMatchRank' : 0,
    'provider' : 'SABRE',
    'hackerFare' : false,
    'enabled' : true,
    'vipEligible' : false,
    'relevantForFairPrice' : true,
    'scheduleOnly' : false,
    'passPlusEligibleType' : 'NONE',
    'refundableInfo' : {
      'exchangeBeforeDeparture' : {
        'applicable' : true,
        'penaltyAmount' : 200.00
      },
      'exchangeAfterDeparture' : {
        'applicable' : false,
        'penaltyAmount' : 0
      },
      'refundBeforeDeparture' : {
        'applicable' : false,
        'penaltyAmount' : 0
      },
      'refundAfterDeparture' : {
        'applicable' : false,
        'penaltyAmount' : 0
      },
      'infoAvailable' : true
    },
    'priceBreakdown' : null,
    'highRiskBooking' : false,
    'enableChat' : false,
    'fares' : {
      'id' : 'e2e36b34-b98a-4c7f-814c-c9bd2af7df41',
      'fares' : [ {
        'uuid' : '3f188c98-9f17-476c-bc75-e28fbc6d7b12',
        'validatingCarrier' : 'AA',
        'price' : {
          'basePrice' : 415.810000000000000000000000000000,
          'tax' : 45.390000000000000000000000000000,
          'agencyCurrency' : 'USD',
          'agencyCurrencyConversion' : 1,
          'sourceCurrency' : 'USD',
          'sourceCurrencyConversion' : 1,
          'resortFee' : 0,
          'resortFeeDisclaimer' : null,
          'bookingFee' : 0,
          'tripFeeQuotes' : [ ],
          'vipFee' : 0,
          'exchangeAmount' : 0,
          'exchangeFee' : 0,
          'airlineFee' : 0,
          'creditCardFee' : 0,
          'startingPrice' : false,
          'points' : 1000,
          'numDays' : 0,
          'cancelationPolicy' : null,
          'outOfPolicy' : false,
          'policyViolationList' : [ ],
          'totalPrice' : 461.200000000000000000000000000000,
          'totalNetCharge' : 461.200000000000000000000000000000,
          'currency' : 'USD'
        },
        'basicEconomy' : false,
        'type' : 'ECONOMY',
        'segments' : [ {
          'fareClass' : 'K',
          'cabin' : 'ECONOMY',
          'fareBasis' : 'K0AJZNN1',
          'seatsRemaining' : 9
        } ],
        'soldOut' : false,
        'description' : null,
        'refundableInfo' : {
          'exchangeBeforeDeparture' : {
            'applicable' : true,
            'penaltyAmount' : 200.00
          },
          'exchangeAfterDeparture' : {
            'applicable' : false,
            'penaltyAmount' : 0
          },
          'refundBeforeDeparture' : {
            'applicable' : false,
            'penaltyAmount' : 0
          },
          'refundAfterDeparture' : {
            'applicable' : false,
            'penaltyAmount' : 0
          },
          'infoAvailable' : true
        },
        'brand' : null,
        'mainFare' : true,
        'priceValidated' : true,
        'bookFullFare' : false,
        'productId' : null,
        'businessClass' : false,
        'refundable' : false,
        'mixedClass' : false
      } ],
      'allowFareSelection' : false,
      'cheapestFareId' : '3f188c98-9f17-476c-bc75-e28fbc6d7b12'
    },
    'selectedFareId' : null,
    'manualZendeskTicket' : null,
    'priceValidated' : false,
    'fullReturnFlightsFetched' : false,
    'fareUpgradeMaybeAvailable' : false,
    'shouldFetchMoreFares' : false,
    'previousBookingsInfo' : null,
    'lowCost' : false,
    'priceInfo' : {
      'basePrice' : 415.810000000000000000000000000000,
      'tax' : 45.390000000000000000000000000000,
      'agencyCurrency' : 'USD',
      'agencyCurrencyConversion' : 1,
      'sourceCurrency' : 'USD',
      'sourceCurrencyConversion' : 1,
      'resortFee' : 0,
      'resortFeeDisclaimer' : null,
      'bookingFee' : 0,
      'tripFeeQuotes' : [ ],
      'vipFee' : 0,
      'exchangeAmount' : 0,
      'exchangeFee' : 0,
      'airlineFee' : 0,
      'creditCardFee' : 0,
      'startingPrice' : false,
      'points' : 1000,
      'numDays' : 0,
      'cancelationPolicy' : null,
      'outOfPolicy' : false,
      'policyViolationList' : [ ],
      'totalPrice' : 461.200000000000000000000000000000,
      'totalNetCharge' : 461.200000000000000000000000000000,
      'currency' : 'USD'
    },
    'mixedClass' : false,
    'multipleFares' : false,
    'links' : [ {
      'rel' : 'self',
      'href' : 'http://localhost:8080/api/v1/trip/flight/searches/657f2bb7-eb72-4282-a30a-95d91638f6b6/departures/5d0dcf42-7830-4625-af3b-9969475ef78a'
    } ]
  },
  {
    'uuid' : 'b7e1dd46-929c-43e4-8a9a-77854108b593',
    'flight' : {
      'flightSegments' : [
        {
        'uuid' : '59036000-0538-4200-8c83-d80f1d4b5cba',
        'airlineCode' : 'B6',
        'airlineName' : 'JetBlue',
        'operatingAirlineCode' : null,
        'operatingAirlineName' : null,
        'operatingFlightNumber' : '1435',
        'flightNumber' : '1435',
        'stopQuantity' : 0,
        'elapsedTimeMinutes' : 88,
        'departureDateAndTime' : '2018-07-05T12:37:00.000',
        'arrivalDateAndTime' : '2018-07-05T14:05:00.000',
        'estimatedDepartureDateTime' : null,
        'estimatedArrivalDateTime' : null,
        'departureTerminal' : null,
        'arrivalTerminal' : null,
        'departureAirportCode' : 'SFO',
        'arrivalAirportCode' : 'LGB',
        'airlineLogoUrl' : null,
        'flightClass' : 'ECONOMY',
        'airplaneName' : 'AIRBUS',
        'carrierLocator' : null,
        'departureGate' : null,
        'departureGateChanged' : false,
        'arrivalGate' : null,
        'baggageClaim' : null,
        'status' : 'CONFIRMED',
        'fareClass' : 'R',
        'segmentNumber' : null,
        'seatsRemaining' : 9,
        'seatSelectionStatusCode' : null,
        'highResAirlineLogoUrl' : 'https://s3.amazonaws.com/tripactions-airline-logos/B6.png',
        'departureZonedDateTime' : '2018-07-05T12:37:00-07:00',
        'arrivalZonedDateTime' : '2018-07-05T14:05:00-07:00',
        'estimatedDepartureZonedDateTime' : null,
        'estimatedArrivalZonedDateTime' : null,
        'stopsString' : ''
      }, {
        'uuid' : 'a419c891-5a85-453f-b13a-6cb611daa074',
        'airlineCode' : 'B6',
        'airlineName' : 'JetBlue',
        'operatingAirlineCode' : null,
        'operatingAirlineName' : null,
        'operatingFlightNumber' : '514',
        'flightNumber' : '514',
        'stopQuantity' : 0,
        'elapsedTimeMinutes' : 323,
        'departureDateAndTime' : '2018-07-05T15:25:00.000',
        'arrivalDateAndTime' : '2018-07-05T23:48:00.000',
        'estimatedDepartureDateTime' : null,
        'estimatedArrivalDateTime' : null,
        'departureTerminal' : null,
        'arrivalTerminal' : null,
        'departureAirportCode' : 'LGB',
        'arrivalAirportCode' : 'JFK',
        'airlineLogoUrl' : null,
        'flightClass' : 'ECONOMY',
        'airplaneName' : 'AIRBUS',
        'carrierLocator' : null,
        'departureGate' : null,
        'departureGateChanged' : false,
        'arrivalGate' : null,
        'baggageClaim' : null,
        'status' : 'CONFIRMED',
        'fareClass' : 'R',
        'segmentNumber' : null,
        'seatsRemaining' : 9,
        'seatSelectionStatusCode' : null,
        'highResAirlineLogoUrl' : 'https://s3.amazonaws.com/tripactions-airline-logos/B6.png',
        'departureZonedDateTime' : '2018-07-05T15:25:00-07:00',
        'arrivalZonedDateTime' : '2018-07-05T23:48:00-04:00',
        'estimatedDepartureZonedDateTime' : null,
        'estimatedArrivalZonedDateTime' : null,
        'stopsString' : ''
      } ],
      'durationMinutes' : 491,
      'connectionCount' : 1,
      'mixedClass' : false,
      'basicEconomy' : false,
      'airFareType' : null,
      'valid' : true,
      'totalLayoverMinutes' : 80
    },
    'startingPrice' : {
      'basePrice' : 424.200000000000000000000000000000,
      'tax' : 54.620000000000000000000000000000,
      'agencyCurrency' : 'USD',
      'agencyCurrencyConversion' : 1,
      'sourceCurrency' : null,
      'sourceCurrencyConversion' : 0,
      'resortFee' : 0,
      'resortFeeDisclaimer' : null,
      'bookingFee' : 0,
      'tripFeeQuotes' : [ ],
      'vipFee' : 0,
      'exchangeAmount' : 0,
      'exchangeFee' : 0,
      'airlineFee' : 0,
      'creditCardFee' : 0,
      'startingPrice' : false,
      'points' : 0,
      'numDays' : 0,
      'cancelationPolicy' : null,
      'outOfPolicy' : false,
      'policyViolationList' : [ ],
      'totalPrice' : 478.820000000000000000000000000000,
      'totalNetCharge' : 478.820000000000000000000000000000,
      'currency' : 'USD'
    },
    'loyaltyCardUuid' : null,
    'applicableFFPrograms' : [ ],
    'promotion' : null,
    'bestMatchRank' : 1,
    'provider' : 'SABRE',
    'hackerFare' : false,
    'enabled' : true,
    'vipEligible' : false,
    'relevantForFairPrice' : false,
    'scheduleOnly' : false,
    'passPlusEligibleType' : 'NONE',
    'refundableInfo' : {
      'exchangeBeforeDeparture' : {
        'applicable' : true,
        'penaltyAmount' : 150.00
      },
      'exchangeAfterDeparture' : {
        'applicable' : true,
        'penaltyAmount' : 150.00
      },
      'refundBeforeDeparture' : {
        'applicable' : true,
        'penaltyAmount' : 150.00
      },
      'refundAfterDeparture' : {
        'applicable' : false,
        'penaltyAmount' : 0
      },
      'infoAvailable' : true
    },
    'priceBreakdown' : null,
    'highRiskBooking' : false,
    'enableChat' : false,
    'fares' : {
      'id' : '25a3efb0-239f-4f9d-af12-94cbe78e635d',
      'fares' : [ {
        'uuid' : '25d18793-17ad-4946-af0b-bfc200af8b73',
        'validatingCarrier' : 'B6',
        'price' : {
          'basePrice' : 424.200000000000000000000000000000,
          'tax' : 54.620000000000000000000000000000,
          'agencyCurrency' : 'USD',
          'agencyCurrencyConversion' : 1,
          'sourceCurrency' : 'USD',
          'sourceCurrencyConversion' : 1,
          'resortFee' : 0,
          'resortFeeDisclaimer' : null,
          'bookingFee' : 0,
          'tripFeeQuotes' : [ ],
          'vipFee' : 0,
          'exchangeAmount' : 0,
          'exchangeFee' : 0,
          'airlineFee' : 0,
          'creditCardFee' : 0,
          'startingPrice' : false,
          'points' : 0,
          'numDays' : 0,
          'cancelationPolicy' : null,
          'outOfPolicy' : false,
          'policyViolationList' : [ ],
          'totalPrice' : 478.820000000000000000000000000000,
          'totalNetCharge' : 478.820000000000000000000000000000,
          'currency' : 'USD'
        },
        'basicEconomy' : false,
        'type' : 'REFUNDABLE',
        'segments' : [ {
          'fareClass' : 'R',
          'cabin' : 'ECONOMY',
          'fareBasis' : 'RH0AUEN5',
          'seatsRemaining' : 9
        }, {
          'fareClass' : 'R',
          'cabin' : 'ECONOMY',
          'fareBasis' : 'RH0AUEN5',
          'seatsRemaining' : 9
        } ],
        'soldOut' : false,
        'description' : null,
        'refundableInfo' : {
          'exchangeBeforeDeparture' : {
            'applicable' : true,
            'penaltyAmount' : 150.00
          },
          'exchangeAfterDeparture' : {
            'applicable' : true,
            'penaltyAmount' : 150.00
          },
          'refundBeforeDeparture' : {
            'applicable' : true,
            'penaltyAmount' : 150.00
          },
          'refundAfterDeparture' : {
            'applicable' : false,
            'penaltyAmount' : 0
          },
          'infoAvailable' : true
        },
        'brand' : null,
        'mainFare' : true,
        'priceValidated' : true,
        'bookFullFare' : false,
        'productId' : null,
        'businessClass' : false,
        'refundable' : true,
        'mixedClass' : false
      } ],
      'allowFareSelection' : false,
      'cheapestFareId' : '25d18793-17ad-4946-af0b-bfc200af8b73'
    },
    'selectedFareId' : null,
    'manualZendeskTicket' : null,
    'priceValidated' : false,
    'fullReturnFlightsFetched' : false,
    'fareUpgradeMaybeAvailable' : false,
    'shouldFetchMoreFares' : false,
    'previousBookingsInfo' : {
      'type' : 'YOU_BOOKED',
      'caption' : 'Booked',
      'subCaption' : 'by you',
      'colleagueRewardsCaption' : null,
      'userBookingsCount' : 1,
      'companyRecentBookingsCount' : 1,
      'allRecentBookingsCount' : 0,
      'bookingColleagueName' : null,
      'bookingColleaguePictureUrl' : null,
      'colleagueOnSameTrip' : false
    },
    'lowCost' : false,
    'priceInfo' : {
      'basePrice' : 424.200000000000000000000000000000,
      'tax' : 54.620000000000000000000000000000,
      'agencyCurrency' : 'USD',
      'agencyCurrencyConversion' : 1,
      'sourceCurrency' : 'USD',
      'sourceCurrencyConversion' : 1,
      'resortFee' : 0,
      'resortFeeDisclaimer' : null,
      'bookingFee' : 0,
      'tripFeeQuotes' : [ ],
      'vipFee' : 0,
      'exchangeAmount' : 0,
      'exchangeFee' : 0,
      'airlineFee' : 0,
      'creditCardFee' : 0,
      'startingPrice' : false,
      'points' : 0,
      'numDays' : 0,
      'cancelationPolicy' : null,
      'outOfPolicy' : false,
      'policyViolationList' : [ ],
      'totalPrice' : 478.820000000000000000000000000000,
      'totalNetCharge' : 478.820000000000000000000000000000,
      'currency' : 'USD'
    },
    'mixedClass' : false,
    'multipleFares' : false,
    'links' : [ {
      'rel' : 'self',
      'href' : 'http://localhost:8080/api/v1/trip/flight/searches/657f2bb7-eb72-4282-a30a-95d91638f6b6/departures/b7e1dd46-929c-43e4-8a9a-77854108b593'
    } ]
  },
  ]
